### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by BrendanBall** [cdmbase/graphql-nats-subscriptions#4]
Hi

Is this being used in production anywhere or is this just a toy sideproject? 
Can you please add a license to this project so that I can decide whether to fork it or create my own from scratch if you're not maintaining this project?

**Comment by veeramarni** [comment]
Yes, it is maintained and used in production. If you need any feature please let me know or create PR.

**Comment by BrendanBall** [comment]
I was wondering about the other open issues like [issue 3](https://github.com/cdmbase/graphql-nats-subscriptions/issues/3) that I also experienced but you haven't commented on.
